CREATE SEQUENCE AS_Sequence
    START WITH 50002
    INCREMENT BY 1;

CREATE TABLE ACCOUNT_TYPE
(
  ACCOUNT_TYPE_ID   BIGINT    NOT NULL,
  MNEMONIC  VARCHAR(100)  NOT NULL UNIQUE,
  ACCOUNT_TYPE_NAME VARCHAR(255)    NOT NULL,
  CREATION_DATE DATE    NOT NULL,
  PRIMARY KEY (ACCOUNT_TYPE_ID)
);

CREATE TABLE Account_Test
(
  TX_ID   BIGINT    NOT NULL,
  ACCOUNT_TYPE_ID   BIGINT    NOT NULL,
  MEMBER_ID   BIGINT    NOT NULL,
  AMOUNT   BIGINT    NOT NULL,
  TX_DATE DATE    NOT NULL,
  PRIMARY KEY (TX_ID),
  CONSTRAINT FK_ACCOUNT_TYPE_ID FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE (ACCOUNT_TYPE_ID)
);